[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "plain<1.0.0",
]

[tool.uv]
dev-dependencies = [
    "plain-dev<1.0.0",
    "plain-pytest<1.0.0",
]
