#!/bin/sh -e

echo "Installing dependencies with poetry"
poetry config installer.parallel false  # Avoid race condition in git repo cloning
poetry config virtualenvs.in-project true
poetry install

echo "Installing bolt pre-commit hooks"
poetry run bolt pre-commit --install

if [ ! -f .env ]; then
    echo "Copying .env.example to .env"
    cp .env.example .env
fi
